### ISSUE TITLE
My pet

### ISSUE THREAD

**Issue by Headsplitter** [Warcrusade/Warcrusade#22]
**My pet:**

Description of the problem or issue here.

**still only rank 2:**

Tell us what happens.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by Headsplitter** [comment]
ingame name Headhunter

**Comment by mayday2013** [comment]
so where is the problem?
