### ISSUE TITLE
[Shattered Sun Pendant of Acumen

### ISSUE THREAD

**Issue by 3b16ci99r** [Warcrusade/Warcrusade#26]
**Description:**

Does not work

**Current behaviour:**

Neck have 0% proc , I have 999/1000 scryers rep. but this neck do nothing , I can dot and dmg with spells but neck never proc 

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by TeronGore** [comment]
Invalid report, works fine please check your combat log next time
