### ISSUE TITLE
warsong gulch info table bug

### ISSUE THREAD

**Issue by legendwarcrusade** [Warcrusade/Warcrusade#5]
**Description:**

in WSG when you check the team roster its showing all alliance players together and horde players together, as if they are in one team. so its not recognizing the crossfaction factor. 
Also flag cap indicator at the top screen is bugged.

**Current behaviour:**
 
I believe that this bug is also messing with the flag caps counter at the top of the screen. it doesn't seem to be right. 
for example an Alliance player on a horde team grabbing the alliance flag will show the horde flag as taken. 
but when the flag is capped it shows it correctly.

**Expected behaviour:**

**Comment by TeronGore** [comment]
This is just visual, i'll take it at hold
