### ISSUE TITLE
Terestian Illhoof bugged

### ISSUE THREAD

**Issue by RudeBugReports** [Warcrusade/Warcrusade#8]
**Description:**

![image](https://user-images.githubusercontent.com/48422705/54155629-8bf99300-4412-11e9-9a59-a8639ffb58df.png)

**Current behaviour:**

Stands in hallway

**Expected behaviour:**

Supposed to be in room

**Steps to reproduce the problem:**

We died the first time, he sat in hallway.. Tried to reset, for him to go into room, and he went back to same location.

**Comment by First1993** [comment]
And ims from him need to do fireballs not attack with mele

**Comment by TeronGore** [comment]
I can't reproduce this issue, I'v died in the hall and he did return to his location
